### ISSUE TITLE
Add ping utility

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#463]
There's interest in adding a ping utility to the "i" menu where you could ping a certain IP address or domain. I think we have most of the code needed for this on iOS, but on Android we'd need #159 first.

**Comment by apike** [comment]
@rachteo Let's chat about this soon and put together enough requirements to do a design pass on this feature.

**Comment by rachteo** [comment]
Split the existing traceroute button into two:
![ping-button](https://user-images.githubusercontent.com/1234900/40249526-205ddc92-5a88-11e8-8bcd-c3179e24a534.png)

When the ping is started, results are displayed in a format consistent with traceroute results. When the ping (and traceroute) results are x'd out of, user is returned to previous info screen rather than to the reset globe view.
![ping-results](https://user-images.githubusercontent.com/1234900/40249562-3bf29e34-5a88-11e8-8bd6-a2e299b763f1.png)

Ping for Cogeco locations is added to info menu:
![ping-info](https://user-images.githubusercontent.com/1234900/40249637-788c9f66-5a88-11e8-9043-324a1c750c8c.png)

Selecting "Ping Cogeco Peer1" displays a list of locations alphabetically grouped by continent. Tapping any of the locations will display the selected node on the network with the option to Ping (and possibly also Traceroute)
![ping-locations](https://user-images.githubusercontent.com/1234900/40249661-877a8862-5a88-11e8-9f56-b06546612c07.png)

**Comment by apike** [comment]
Great, thanks Rach!

**Comment by apike** [comment]
Some progress on this was made here: https://github.com/steamclock/internetmap/tree/rnm/463-ping

**Comment by ssawchenko** [comment]
@apike Digging back through Slack there was conversations about what IPs to use for pings. Rob indicated that many of the ASNs were failing to be pingable. Do you recall where we ended up on the matter of what IPs we should be using, and where we can get the list of Peer 1 ASNs / IPs for the "Ping Us" page? 

June 22nd 2018

rob [12:31 PM]
Ok. I haven’t found a single node displayed in the app that will actually respond to pings yet. @apike do we still want to implement this feature? I think it’s going to feel pretty broken.

shayla [12:31 PM]
How is traceroute working?

rob [12:33 PM]
I don’t believe traceroute requires a response from the server in the same way ping does

apike [12:36 PM]
If it won’t work for most nodes, then I suppose we’ll only want to offer it for the peer 1 data centers

nigel [12:37 PM]
Hmm. if *nothing* is working that does suggest it’s something weird going on with our data. Where are the IP addresses that you are using for the pings coming from?

apike [12:37 PM]
That’s what they’d originally asked for, and I pitched allowing you to ping anything

rob [12:38 PM]
@nigel `ASNRequest fetchIPsForASN:node.asn ...`. The same address lookup method we use for traceroute.
@apike do you have the addresses of their data centers?

nigel [12:50 PM]
Ahh, okay. I think I get it. That will give you a list of IPs that are owned by that ASN, but there is no guarantee that any given IP address actually has a server on it, or that it’s a server that is configured to respond to pings. That’s fine for traceroute because the nature of the routing protocol means that the last hop to a non-functional server owned by a given ASN should always be the same as the last hop to a valid server in that range. So even if you pick an invalid one to traceroute to, you will get the correct route (we always show the last segment being to the target node, even if we never get a valid traceroute response from it).
But for pings, if you don’t have a responsive server, you are out of luck. Not sure if there is a good way to find a pingable server in the range, other than just trying a bunch of them.

apike [12:53 PM]
No, I’ll start an email thread to try and track down those IPs

nigel [1:01 PM]
One potential approach that would be a little cleaner than just triggering dozens or hundreds of pings from the app would be to track a “representative” IP address for each ASN. So write a little tool server side that basically probed each ASNs IP range to try and find a server that responds to pings , then store that in each ASNs data (probably on the server side) and periodically re-check to make sure that the representative IP for a given range is still up and responding to pings.

rob [1:03 PM]
How big are the ranges of a typical asn?

nigel [1:17 PM]
Can go into the millions. Apple has over 16 million (https://ipinfo.io/AS714). There might be cleverer ways to nail that down then trying all of them though. If we can get a representative domain for a ASN, we can nslookup  that to get a reasonable public facing IP (not sure how easy that’d be to automate though). We might be able to get a valid server using the same trick of trace-routing to an invalid IP that traceroute itself uses (do a traceroute to a random IP in the range, but watch the response for other ip addresses from that ASN, and then turn around and ping that IP address instead).
ipinfo.io
AS714 Apple Inc. - ipinfo.io
AS714 Apple Inc. Network Information, IP Address Ranges and Whois Details

rob [3:56 PM]
So I’ve tried using `nmap` to scan ranges of IPs in different blocks but it seems like “up” ips are very very sparse. the lookups are slow, about 0.5 seconds per IP.

I tried pinging the hops on the traceroute and it worked for some after hopping back a few nodes, but we’d need to lookup the ASN of the hop to verify it’s actually in the same ASN…

Is there value in knowing the ping for an arbitrary IP owned by an ASN? I don’t really have a sense of why people might be curious about this type of information and if this would help them at all.

apike [3:57 PM]
Map of the Internet is mostly about curiosity in general – is there value in knowing the ASN exists? Or what your traceroute to it would be? Not *really*, at least not business value.
But it felt less cynical to allow ping to arbitrary places rather than just to Peer 1 locations.
And generally nicer

**Comment by apike** [comment]
@robmaceachern It seems like the ideal experience would be to convert the hostname to a ASN, then show that ASN in the map with the ping results.

![image](https://user-images.githubusercontent.com/129240/52820481-f4965f80-3060-11e9-862e-89be43e1ec91.png)

**Comment by apike** [comment]
@ssawchenko They're working on getting us server names and hostnames for the pings, but let's use 2-3 placeholders for now until they have that. From what Rob was saying, pinging an ASN seems not a priority.

**Comment by ssawchenko** [comment]
Sweet. Seems like we should be able to get hostname -> IP -> ASN pretty easily given the APIs we already have available. Concerns would be:

* We do not have an ASN node for the give IP (our data set is now running a year old, this could be possible).
* This IP we end up with is not Pingable (not sure if this is possible given the way DNS lookup works, but just putting it out there)

**Comment by robmaceachern** [comment]
> * This IP we end up with is not Pingable (not sure if this is possible given the way DNS lookup works, but just putting it out there)

Yeah that is definitely possible. Here's an example with `microsoft.com`:
```
# Lookup
host microsoft.com
microsoft.com has address 40.112.72.205
microsoft.com has address 40.113.200.201
microsoft.com has address 104.215.148.63
microsoft.com has address 13.77.161.179
microsoft.com has address 40.76.4.15
microsoft.com mail is handled by 10 microsoft-com.mail.protection.outlook.com.

# Ping
ping 40.112.72.205
PING 40.112.72.205 (40.112.72.205): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```

**Comment by apike** [comment]
@robmaceachern Once you've sorted the code review points with Nigel, this looks good to merge functionality-wise. I've filed a follow-up issue for some top UI polish items.
