### ISSUE TITLE
Change order of menus, change about page button

### ISSUE THREAD

**Issue by jotkali** [steamclock/internetmap#469]
- swap location of about and contact entries
- Change button at bottom of About to open a web view controller for cogecopeer1.com instead of going to contact as it does now
- Implement iOS menu changes on Android

**Comment by ssawchenko** [comment]
cogecopeer1.com does not load quickly. I have been attempting to move to an embedded WebView (instead of launching an external browser), however by doing this we lose the loading bar at the top of the native browser. Because the url takes so long to load, the user cannot tell that the page is actually loading during this time - the app seems unresponsive. I attempted to add a loading spinner to give feedback to the user, however, there is still a number of seconds after the page is finished loading (I believe while the HTML is being rendered) that the app will appear unresponsive. 

Due to this I am keeping the method of loading the urls in an external browser, unless the client indicates that they really want them embedded.

**Comment by apike** [comment]
This is now all good AFAIK.
