### ISSUE TITLE
Fix iPhone X elements that are too close to screen edges

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#484]
We should build master on Xcode for the iPhone X simulator, note what issues there are in this issue, and prep a patch.

**Comment by abey** [comment]
**iPhone X Simulator Test Run**

- An extension of Issue #474, everything on iPhone X Simulator (on MacBook Air) is awfully slow.
- We may have to shift the views a little higher to prevent UI issues.
![screen shot 2017-10-23 at 10 46 36 am](https://user-images.githubusercontent.com/11465329/31904314-be2dbc18-b7df-11e7-8ab3-b0033ef5f4d7.png)
- Credits page close button (I don't think we should change this as it doesn't look bad)
![screen shot 2017-10-23 at 10 50 42 am](https://user-images.githubusercontent.com/11465329/31904449-24c715aa-b7e0-11e7-8122-20c70fc67abb.png)
- Decrease the size of "Visit cogecopeer1.com" button on About Cogeco Peer 1 page since the lower portion of the letter "g" is not visible.
![screen shot 2017-10-23 at 11 04 05 am](https://user-images.githubusercontent.com/11465329/31905224-4c85cda0-b7e2-11e7-9e74-dc02f75deb54.png)

Should I open new issues for any of these @apike?

**Comment by apike** [comment]
Definitely all three of those are too close to the edges, so we'll need to do a pass on this. It looks like the items too close to the bottom would be fine to bump up, but the X button could use a new look/asset that will work both on the X and on other devices, probably by insetting it from the corner, and maybe making it circular. @rachteo can you do a quick pass on that?

**Comment by rachteo** [comment]
<img src="https://user-images.githubusercontent.com/1234900/32125562-66a8e9d2-bb21-11e7-8c6e-c2ad8f52fe0c.png" width="400">
Can we bump the menu icons down 40pt and distribute them evenly across the top of the screen?

**Comment by rachteo** [comment]
For the close button, I'd suggest just moving it further down so that it's in line with where the menu would be, which is in line with what Apple seems to be doing with their own apps

**Comment by apike** [comment]
Seems reasonable to me - Is 40pt the "safe area margin" that we get from the iOS APIs?

Also, spacing the icons evenly on iPhones seems reasonable, as long as it doesn't look silly on the iPhone Plus.

**Comment by ssawchenko** [comment]
I have applied the safe area constraints to all ViewControllers except CreditsViewController. CreditsViewController does not have a storyboard and setting up the constraints in Objective C is rather verbose. I looked into converting into Swift, however, I ran into a bunch of issues (including a linker error) - if @nbrooke could look into converting CreditsViewController to swift I feel it would a better use of the project hours.

Once again, I have done the iPhoneX conversion on other pages, I just need CreditsViewController converted to swift or converted to use a Storyboard.

**Comment by nbrooke** [comment]
Did the Swift conversion of CreditsViewController yesterday, it's ready to try as pull request #492

**Comment by ssawchenko** [comment]
Whoops, I see that PR in my email inbox (sorry!). I'll check it out.

**Comment by ssawchenko** [comment]
@rachteo 
> Can we bump the menu icons down 40pt and distribute them evenly across the top of the screen? And conversely, bump up the timeline and buttons and things by 40pt

Do you mean 40pt from the top of the device, or 40pts from the top of iPhoneX's "safe area"? Applying 40pts from the safe area puts the menu here:
![image](https://user-images.githubusercontent.com/5217641/32631553-722c709c-c555-11e7-8286-26ce4c6d6697.png)

Adhering to the top of the safe area puts the menu here:
![image](https://user-images.githubusercontent.com/5217641/32631610-96e0c23a-c555-11e7-8deb-9bad54d22067.png)

**Comment by apike** [comment]
@ssawchenko Definitely the second one :)

**Comment by ssawchenko** [comment]
I realized after I asked that it was a silly question. I perhaps need another cup of coffee ;)
