### ISSUE TITLE
Base of map is too high on screen during positioning

### ISSUE THREAD

**Issue by apike** [steamclock/internetmap#522]
When you're looking at the map you tend to want it to be center screen, but to place the map reasonably nearby, you need to kind of point the map such that it's mostly off the top of the screen, tap place, then pan back up to see the placement.

**Comment by nbrooke** [comment]
This is a somewhat inherent problem with the current placement approach, as outlined in #514. With the current approach you need to position something "on" the ground, but because we want the map in the air, so the thing you are placing basically has to be well below it.

The options we have available:
- Keep the current behaviour, but try and make what is happening move obvious by showing what you are doing (per #514), by making the invisible "strut" you are placing the globe on visible.
 - Have the raycast that we do to the ground aim downwards to some degree, so the spot you are placing on the ground is like 1/4 of the way up the screen rather than 1/2 way. this would fix it for some distances, but not all.
- Instead of trying to find a surface to place it on, place the centre of the globe, using a fixed distance from the device (so, for example, you always place the globe 6 feet in front of wherever the camera is pointing). Probably with some logic to make sure that it doesn't go into the ground (do a recast down from the position we are placing to see if it hits the ground plane, and move it up if it does). This would solve this problem, and is probably a little more intuitive, and lets you change the height of the globe, but would make it harder to place at an exact location then the current approach.

Any thoughts on those options?

**Comment by apike** [comment]
Both the casting at an angle and the using a fixed distance approach both seem interesting to me - maybe let's start with trying whichever is easier?

**Comment by nbrooke** [comment]
7c2c07df5 implements the fixed distance in front of camera placement. The aim down one didn't give very good results, and this also doesn't have any weirdness due to the hit-tests being somewhat unstable like the hit test based placement did.
